name: Sync Fork

on:
  schedule:
    - cron: '0 1  * * *' # every day
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: anatawa12/fork-sync-all-branches@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
